WHENEVER SQLERROR EXIT FAILURE ROLLBACK
SET DEFINE OFF
SET SQLBLANKLINES ON
SET SERVEROUTPUT ON
SPOOL /tmp/compliant_multi_block.log

CREATE OR REPLACE PROCEDURE a AS
BEGIN NULL; END;
/

CREATE OR REPLACE PROCEDURE b AS
BEGIN NULL; END;
/

SPOOL OFF
EXIT;
