WHENEVER SQLERROR EXIT FAILURE ROLLBACK
SET DEFINE OFF
SET SQLBLANKLINES ON
SET SERVEROUTPUT ON
SPOOL /tmp/compliant_type_body.log

CREATE OR REPLACE TYPE BODY my_type AS
  MEMBER FUNCTION val RETURN NUMBER IS
  BEGIN RETURN 1; END;
END;
/

SPOOL OFF
EXIT;
