WHENEVER SQLERROR EXIT FAILURE ROLLBACK
SET DEFINE OFF
SET SQLBLANKLINES ON
SET SERVEROUTPUT ON
SPOOL /tmp/compliant_package_spec.log

CREATE OR REPLACE PACKAGE pkg AS
  PROCEDURE foo;
END pkg;
/

SPOOL OFF
EXIT;
