WHENEVER SQLERROR EXIT FAILURE ROLLBACK
SET DEFINE OFF
SET SQLBLANKLINES ON
SET SERVEROUTPUT ON
SPOOL /tmp/compliant_package_body.log

CREATE OR REPLACE PACKAGE BODY pkg AS
  PROCEDURE foo AS
  BEGIN
    NULL;
  END foo;
END pkg;
/

SPOOL OFF
EXIT;
