WHENEVER SQLERROR EXIT FAILURE ROLLBACK
SET DEFINE OFF
SET SQLBLANKLINES ON
SET SERVEROUTPUT ON
SPOOL /tmp/compliant_procedure.log

CREATE OR REPLACE PROCEDURE do_work AS
BEGIN
  INSERT INTO log_table (msg) VALUES ('done');
  COMMIT;
END do_work;
/

SPOOL OFF
EXIT;
