WHENEVER SQLERROR EXIT FAILURE ROLLBACK
SET DEFINE OFF
SET SQLBLANKLINES ON
SET SERVEROUTPUT ON
SPOOL /tmp/bad_missing_slash_trigger.log

-- ERROR: Trigger not terminated with /
CREATE OR REPLACE TRIGGER trg
BEFORE INSERT ON t
BEGIN
  NULL;
END;

SPOOL OFF
EXIT;
