-- ERROR: empty line inside PL/SQL block without SET SQLBLANKLINES ON
WHENEVER SQLERROR EXIT FAILURE ROLLBACK
SET DEFINE OFF
SET SERVEROUTPUT ON
SPOOL x.log

CREATE OR REPLACE PROCEDURE foo AS
BEGIN

  NULL;
END foo;
/

EXIT;
