WHENEVER SQLERROR EXIT FAILURE ROLLBACK
SET DEFINE OFF
SET SQLBLANKLINES ON
SET SERVEROUTPUT ON
SPOOL /tmp/bad_missing_semicolon_dml.log

-- ERROR: INSERT missing terminating semicolon
INSERT INTO t VALUES (1)
COMMIT;

SPOOL OFF
EXIT;
