WHENEVER SQLERROR EXIT FAILURE ROLLBACK
SET DEFINE OFF
SET SQLBLANKLINES ON
SET SERVEROUTPUT ON
SPOOL /tmp/bad_missing_slash_procedure.log

-- ERROR: PL/SQL block not terminated with /
CREATE OR REPLACE PROCEDURE foo AS
BEGIN
  NULL;
END foo;

SPOOL OFF
EXIT;
