WHENEVER SQLERROR EXIT FAILURE ROLLBACK
SET DEFINE OFF
SET SQLBLANKLINES ON
SET SERVEROUTPUT ON
SPOOL /tmp/bad_no_commit_merge.log

-- WARNING: MERGE without COMMIT or ROLLBACK
MERGE INTO t USING src ON (t.id = src.id)
WHEN MATCHED THEN UPDATE SET t.val = src.val;

SPOOL OFF
EXIT;
