WHENEVER SQLERROR EXIT FAILURE ROLLBACK
SET DEFINE OFF
SET SQLBLANKLINES ON
SET SERVEROUTPUT ON
SPOOL /tmp/bad_no_commit.log

-- WARNING: DML without COMMIT or ROLLBACK
INSERT INTO t VALUES (1);

SPOOL OFF
EXIT;
