WHENEVER SQLERROR EXIT FAILURE ROLLBACK
SET DEFINE OFF
SET SQLBLANKLINES ON
SET SERVEROUTPUT ON
SPOOL /tmp/bad_missing_slash_function.log

-- ERROR: PL/SQL block not terminated with /
CREATE OR REPLACE FUNCTION bar RETURN NUMBER IS
BEGIN
  RETURN 1;
END bar;

SPOOL OFF
EXIT;
