WHENEVER SQLERROR EXIT FAILURE ROLLBACK
SET DEFINE OFF
SET SQLBLANKLINES ON
SET SERVEROUTPUT ON
SPOOL /tmp/bad_missing_semicolon.log

-- ERROR: SELECT missing terminating semicolon
SELECT *
FROM dual
WHERE 1=1

SPOOL OFF
EXIT;
