WHENEVER SQLERROR EXIT FAILURE ROLLBACK
SET DEFINE OFF
SET SQLBLANKLINES ON
SET SERVEROUTPUT ON
SPOOL /tmp/bad_missing_slash_multi_block.log

-- OK: first block has slash
CREATE OR REPLACE PROCEDURE a AS
BEGIN NULL; END;
/

-- ERROR: second block missing slash
CREATE OR REPLACE PROCEDURE b AS
BEGIN NULL; END;

SPOOL OFF
EXIT;
