-- ERROR: substitution variable & used without SET DEFINE OFF
WHENEVER SQLERROR EXIT FAILURE ROLLBACK
SET SQLBLANKLINES ON
SET SERVEROUTPUT ON
SPOOL x.log

INSERT INTO t VALUES (&val);
COMMIT;

EXIT;
